export {ErrorSocket} from './errorSocket'
export {GameSocket} from './gameSocket'
export {RoomSocket} from './roomSocket'
export {ChatSocket} from './chatSocket'
export {FriendsSocket} from './friendsSocket'