export const THROW_MONSTER_CARDS_TO_BATTLEFIELD = 'THROW_MONSTER_CARDS_TO_BATTLEFIELD'
export const DROP_MONSTER_CARDS_FROM_BATTLEFIELD = 'DROP_MONSTER_CARDS_FROM_BATTLEFIELD'
export const SUMMONABLE_BATTLEFIELD = 'SUMMONABLE_BATTLEFIELD'
export const SUMMONENABLE_BATTLEFIELD = 'SUMMONENABLE_BATTLEFIELD'