export const THROW_MONSTER_CARDS_TO_BATTLEFIELD = 'THROW_MONSTER_CARDS_TO_BATTLEFIELD'
export const DROP_MONSTER_CARDS_FROM_BATTLEFIELD = 'DROP_MONSTER_CARDS_FROM_BATTLEFIELD'
export const SUMMONABLE_BATTLEFIELD = 'SUMMONABLE_BATTLEFIELD'
export const SUMMONENABLE_BATTLEFIELD = 'SUMMONENABLE_BATTLEFIELD'
export const THROW_TRAP_CARD_TO_BATTLEFIELD = 'THROW_TRAP_CARD_TO_BATTLEFIELD'
export const DROP_TRAP_CARD_TO_BATTLEFIELD = 'DROP_TRAP_CARD_TO_BATTLEFIELD'

export const REFRESH_ATTACK_TIMES = 'REFRESH_ATTACK_TIMES'
export const MINUS_ATTACK_TIMES   = 'MINUS_ATTACK_TIMES'
export const ACTIVE_BATTLE_FIELD  = 'ACTIVE_BATTLE_FIELD'
export const UNACTIVE_BATTLE_FIELD = 'UNACTIVE_BATTLE_FIELD'

export const TRAPABLE_BATTLEFIELD = 'TRAPABLE_BATTLEFIELD' 
export const TRAPENABLE_BATTLEFIELD = 'TRAPENABLE_BATTLEFIELD'