export const THROW_MONSTER_CARDS_TO_E_BATTLEFIELD = 'THROW_MONSTER_CARDS_TO_E_BATTLEFIELD'
export const DROP_MONSTER_CARDS_FROM_E_BATTLEFIELD = 'DROP_MONSTER_CARDS_FROM_E_BATTLEFIELD'
export const THROW_TRAP_CARD_TO_E_BATTLEFIELD = 'THROW_TRAP_CARD_TO_E_BATTLEFIELD'
export const DROP_TRAP_CARD_TO_E_BATTLEFIELD = 'DROP_TRAP_CARD_TO_E_BATTLEFIELD'

export const REFRESH_E_ATTACK_TIMES = 'REFRESH_E_ATTACK_TIMES'
export const MINUS_E_ATTACK_TIMES   = 'MINUS_E_ATTACK_TIMES'

export const ACTIVE_E_BATTLEFIELD = 'ATTACKABLE_E_BATTLEFIELD'
export const UNACTIVE_E_BATTLEFIELD = 'UNACTIVE_E_BATTLEFIELD' 
export const ACTIVE_ATTACKABLE_E_BATTLEFIELD = 'ACTIVE_ATTACKABLE_E_BATTLEFIELD' 
export const UNACTIVE_ATTACKABLE_E_BATTLEFIELD = 'UNACTIVE_ATTACKABLE_E_BATTLEFIELD' 