export const ADD_E_HANDCARDS = 'ADD_E_HANDCARDS'
export const DELETE_E_HANDCARDS = 'DELETE_E_HANDCARDS'
export const UPDATE_E_HANDCARDS = 'UPDATE_E_HANDCARDS'
export const QUERY_E_HANDCARDS = 'QUERY_E_HANDCARDS'