export const ADD_E_STORECARDS = 'ADD_E_STORECARDS'
export const DELETE_E_STORECARDS = 'DELETE_E_STORECARDS'
export const UPDATE_E_STORECARDS = 'UPDATE_E_STORECARDS'
export const QUERY_E_STORECARDS = 'QUERY_E_STORECARDS'