export const MAX_HP = 8000

export const REDUCE_HP = 'REDUCE_HP'
export const REDUCE_E_HP = 'REDUCE_E_HP'
export const SET_HP = 'SET_HP'
export const SET_E_HP = 'SET_E_HP'

export const START_ANIMATE = 'START_ANIMATE'
export const END_ANIMATE = 'END_ANIMATE'
export const SET_ANIMATE_INFO = 'SET_ANIMATE_INFO'
export const SET_E_ANIMATE_INFO = 'SET_E_ANIMATE_INFO'

export const PUSH_MAGIC_TRIGGER = 'PUSH_MAGICTRIGGER'
export const PUSH_TRAP_TRIGGER = 'PUSH_TRAP_TRIGGER'
export const PUSH_ATTACK_TRIGGER = 'PUSH_ATTACK_TRIGGER'
export const PUSH_EFFECT_TRIGGER = 'PUSH_EFFECT_TRIGGER'

export const DELETE_MAGIC_TRIGGER = 'DELETE_MAGIC_TRIGGER'
export const DELETE_TRAP_TRIGGER = 'DELETE_TRAP_TRIGGER'
export const DELETEE_ATTACK_TRIGGER = 'DELETEE_ATTACK_TRIGGER'
export const DELETE_EFFECT_TRIGGER = 'DELETE_EFFECT_TRIGGER'