export const ROUND_NAME_START            = 'ROUND_NAME_START'
export const ROUND_NAME_GET_CARD_REGULAR = 'ROUND_NAME_GET_CARD_REGULAR'
export const ROUND_NAME_PLAY             = 'ROUND_NAME_PLAY'
export const ROUND_NAME_END              = 'ROUND_NAME_END'
export const ROUND_NAME_SILENT           = 'ROUND_NAME_SILENT'
export const NEXT_ROUND                  = 'NEXT_ROUND'
export const INIT_GOD                    = 'INIT_GOD'
export const FINISH_GAME                 = 'FINISH_GAME'