export const ROUND_NAME_START = 'ROUND_NAME_START'
export const ROUND_NAME_PLAY  = 'ROUND_NAME_PLAY'
export const ROUND_NAME_END   = 'ROUND_NAME_END'
export const ROUND_NAME_SILENT = 'ROUND_NAME_SILENT'