export const GET_ROOMS = 'GET_ROOMS'
export const CREATE_ROOM  = 'ADD_ROOMS'
export const JOIN_ROOM = 'JOIN_ROOM'
export const QUIT_ROOM = 'QUIT_ROOM'
export const SET_ROOMS = 'SET_ROOMS'
export const SET_ROOM  = 'SET_ROOM'
