export const ADD_STORECARDS = 'ADD_STORECARDS'
export const DELETE_STORECARDS = 'DELETE_STORECARDS'
export const UPDATE_STORECARDS = 'UPDATE_STORECARDS'
export const QUERY_STORECARDS = 'QUERY_STORECARDS'